# templates/application.yaml
{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  project: platform
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-org/your-bootstrap-repo
    path: .
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
