{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  generators:
    - list:
        elements:
          - name: foo
            path: apps/foo
  template:
    metadata:
      name: '{{`{{name}}`}}'
    spec:
      project: platform
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      source:
        repoURL: https://github.com/your-org/your-repo
        path: '{{`{{path}}`}}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
{{- end }}
