argocd:
  crds:
    install: true
  server:
    service:
      type: ClusterIP
      annotations: {}
    ingress:
      enabled: false
      ingressClassName: nginx
      annotations: {}
  controller:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  configs:
    params:
      "server.insecure": "true"
    cm:
      application.instanceLabelKey: "argocd.argoproj.io/instance"
    rbac:
      policy.csv: |
        g, your-org:platform, role:admin
      policy.default: role:readonly
  dex:
    enabled: true
  applicationSet:
    enabled: true
