argocd:
  crds:
    install: true
  server:
    service:
      type: ClusterIP
      annotations: {}
    ingress:
      enabled: false
      ingressClassName: nginx
      annotations: {}
  configs:
    params:
      "server.insecure": "true"
  dex:
    enabled: false
  applicationSet:
    enabled: true
