argo-cd:
  crds:
    install: true
  applicationSet:
    enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  configs:
    cm:
      application.instanceLabelKey: "argocd.argoproj.io/instance"

  dex:
    enabled: true
