apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    meta.helm.sh/release-name=argocd
    meta.helm.sh/release-namespace=argocd
  labels:
    app.kubernetes.io/managed-by=Helm
  name: applicationsets.argoproj.io
spec:
  group: argoproj.io
  scope: Namespaced
  names:
    kind: ApplicationSet
    plural: applicationsets
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
